name: Deploy to Cloud Run

on:
    push:
        branches:
            - main

env:
    REGION: ${{ secrets.GCP_REGION }}
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
    deploy-remix:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

            - name: Configure gcloud
              run: |
                  gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
                  gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: Build Remix image
              run: docker build \
                  --build-arg CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
                  --build-arg FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
                  --build-arg FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
                  --build-arg FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
                  -t $REGION-docker.pkg.dev/$PROJECT_ID/musicall/remix:latest -f apps/web/Dockerfile .

            - name: Push Remix image
              run: |
                  docker push $REGION-docker.pkg.dev/$PROJECT_ID/musicall/remix:latest

            - name: Deploy Remix
              uses: google-github-actions/deploy-cloudrun@v2
              with:
                  service: remix-web
                  image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/musicall/remix:latest
                  region: ${{ env.REGION }}

    deploy-server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

            - name: Configure gcloud
              run: |
                  gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
                  gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: Build Server image
              run: docker build \
                  --build-arg CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
                  --build-arg FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
                  --build-arg FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
                  --build-arg FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
                  -t $REGION-docker.pkg.dev/$PROJECT_ID/musicall/server:latest -f apps/server/Dockerfile .

            - name: Push Server image
              run: |
                  docker push $REGION-docker.pkg.dev/$PROJECT_ID/musicall/server:latest

            - name: Deploy Server
              uses: google-github-actions/deploy-cloudrun@v2
              with:
                  service: server
                  image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/musicall/server:latest
                  region: ${{ env.REGION }}
